fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\UserEntity
    from_email:
        address: "info@swiatkonia.pl"
        sender_name: "Światkonia.pl"