#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_add:
   path: /user/new
   controller: App\Controller\UserController::userAdd
user_login:
   path: /user/login
   controller: App\Controller\UserController::userLogin
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"