index:
    path: /
    controller: App\Controller\AdvertController::index
advert_add:
    path: /advert/new
    controller: App\Controller\AdvertController::advertAdd
advert_show_id:
    path: /advert/show/{id}
    controller: App\Controller\AdvertController::advertShowId
advert_edit:
    path: /advert/edit/{id}
    controller: App\Controller\AdvertController::advertEdit 
user_adverts:
    path: advert/showmyadverts
    controller: App\Controller\AdvertController::showMyAdverts
advert_remove:
    path: /advert/remove/{id}
    controller: App\Controller\AdvertController::advertRemove 
advert_activate:
    path: /advert/activate/{id}
    controller: App\Controller\AdvertController::advertActivate
advert_deactivate:
    path: /advert/deactivate/{id}
    controller: App\Controller\AdvertController::advertDeactivate
